//leetcode-389
//TC-O(N)

class Solution {
    public char findTheDifference(String s, String t) {
        Map<Character,Integer> map=new HashMap<>();
        for(int i=0;i<s.length();i++)
        {
            map.put(s.charAt(i),map.getOrDefault(s.charAt(i),0)+1);
        }
        for(int i=0;i<t.length();i++)
        {
             map.put(t.charAt(i),map.getOrDefault(t.charAt(i),0)+1);
        }
        char ans='\0';
        for(int i=0;i<t.length();i++)
        {
            if(map.get(t.charAt(i))%2==1)ans=t.charAt(i);
        }
        return ans;
    }
}
/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"*/
